### ISSUE TITLE
rorpi-readonly.sh can fail if rorpi-ro-setup tar is not unpacked

### ISSUE THREAD

**Issue by amiguelez** [glennmckechnie/rorpi-raspberrypi#1]
Hello

rorpi-readonly.sh fails if rorpi-ro-setup tar exists and is not unpacked, because the script only unpack the tar if it doesn't exist, and it doesn't check if rorpi-ro-setup folder exists.

**Comment by glennmckechnie** [comment]
Thanks for that. Fix is uploaded as [77a3d6d](https://github.com/glennmckechnie/rorpi-raspberrypi/commit/2e779a600ffe50755a99d593f3d30b29e77a3d6d)

I've done a dry run and it should catch the error you've flagged. 
If you're still in a position to do a live test and confirm the fix works, and nothing was broken in the process then, that too, would be appreciated.

**Comment by amiguelez** [comment]
Thank you. I will do a live test on Monday and I will report back.

**Comment by amiguelez** [comment]
It works. Thank you.
